import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Building2, Download, FileSpreadsheet, FileText, Mail, MessageCircle, Save, Trash2, Users, WalletCards } from 'lucide-react';

export interface BranchReport {
  id: number; branchName: string; location: string; manager: string; phone: string; status: string;
  staffCount: string; staffAttendance: string; staffBehavior: string; competitorAround: string;
  marketingStatus: string; leads: string; improveNeeded: string; smartBanking: string; bankingIssues: string;
  feedbackScore: string; customerFeedback: string; oldCustomerCount: string; oldCustomerDetails: string;
  openComplaints: string; complaintNotes: string; remittanceVolume: string; topCorridor: string; notes: string; updatedAt: string;
}

const OMAN_LOCATIONS = ['Muscat - Ruwi', 'Muscat - Al Khuwair', 'Muscat - Al Ghubrah', 'Muscat - Seeb', 'Muscat - Al Amerat', 'Muttrah', 'Bawshar', 'Qurayyat', 'Barka', 'Al Khaburah', 'Suwaiq', 'Sohar', 'Shinas', 'Liwa', 'Saham', 'Ibri', 'Buraimi', 'Nizwa', 'Bahla', 'Samail', 'Bidbid', 'Ibra', 'Sinaw', 'Sur', 'Jalan Bani Bu Ali', 'Duqm', 'Adam', 'Haima', 'Thumrait', 'Salalah', 'Taqah', 'Mirbat', 'Mazyouna', 'Other / custom'];
const STORAGE_KEY = 'aljadeed_branch_reports_v2';
const emptyReport: Omit<BranchReport, 'id' | 'updatedAt'> = {
  branchName: '', location: '', manager: '', phone: '', status: 'Active', staffCount: '', staffAttendance: '', staffBehavior: 'Good', competitorAround: '', marketingStatus: 'Not started', leads: '', improveNeeded: '', smartBanking: 'Not checked', bankingIssues: '', feedbackScore: '', customerFeedback: '', oldCustomerCount: '', oldCustomerDetails: '', openComplaints: '0', complaintNotes: '', remittanceVolume: '', topCorridor: 'BDT', notes: '',
};
interface Props { managerWhatsApp?: string; showToast: (message: string, type?: 'success' | 'error' | 'warning' | 'info') => void; }

const value = (v: unknown) => String(v ?? '').replace(/\s+/g, ' ').trim() || 'N/A';
const reportText = (items: BranchReport[]) => ['🏢 BRANCH-WISE MANAGEMENT REPORT', `Generated: ${new Date().toLocaleString()}`, `Branches covered: ${items.length}`, '', ...items.map((r, i) => [`${i + 1}. ${r.branchName} — ${r.location}`, `Manager: ${value(r.manager)} | Phone: ${value(r.phone)} | Status: ${value(r.status)}`, `Competitors around branch: ${value(r.competitorAround)}`, `Marketing: ${value(r.marketingStatus)} | Leads: ${value(r.leads)}`, `What we need to improve: ${value(r.improveNeeded)}`, `Staff: ${value(r.staffCount)} | Attendance: ${value(r.staffAttendance)} | Behavior: ${value(r.staffBehavior)}`, `Customer feedback: ${value(r.feedbackScore)}/5 — ${value(r.customerFeedback)}`, `Old customers to onboard: ${value(r.oldCustomerCount)} — ${value(r.oldCustomerDetails)}`, `Smart banking: ${value(r.smartBanking)} | Issues: ${value(r.bankingIssues)}`, `Complaints: ${value(r.openComplaints)} — ${value(r.complaintNotes)}`, `Remittance: ${value(r.remittanceVolume)} | Top corridor: ${value(r.topCorridor)}`, `Management notes: ${value(r.notes)}`, ''].join('\n')).join('\n')].join('\n');
const headers = ['Branch', 'Location', 'Manager', 'Status', 'Competitors around branch', 'Marketing status', 'Leads', 'What to improve', 'Staff', 'Attendance', 'Staff behavior', 'Customer feedback', 'Feedback score', 'Old customers', 'Old customer details', 'Smart banking', 'Banking issues', 'Open complaints', 'Complaint notes', 'Remittance volume', 'Top corridor', 'Management notes', 'Updated'];
const row = (r: BranchReport) => [r.branchName, r.location, r.manager, r.status, r.competitorAround, r.marketingStatus, r.leads, r.improveNeeded, r.staffCount, r.staffAttendance, r.staffBehavior, r.customerFeedback, r.feedbackScore, r.oldCustomerCount, r.oldCustomerDetails, r.smartBanking, r.bankingIssues, r.openComplaints, r.complaintNotes, r.remittanceVolume, r.topCorridor, r.notes, r.updatedAt];
const csv = (items: BranchReport[]) => [headers, ...items.map(row)].map((line) => line.map((cell) => `"${String(cell ?? '').replace(/"/g, '""')}"`).join(',')).join('\n');
const download = (content: BlobPart, name: string, type: string) => { const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([content], { type })); link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 500); };

export default function BranchManagement({ managerWhatsApp, showToast }: Props) {
  const [reports, setReports] = useState<BranchReport[]>(() => { try { return JSON.parse(localStorage.getItem(STORAGE_KEY) || '[]'); } catch { return []; } });
  const [form, setForm] = useState({ ...emptyReport }); const [editingId, setEditingId] = useState<number | null>(null);
  useEffect(() => localStorage.setItem(STORAGE_KEY, JSON.stringify(reports)), [reports]);
  const set = (key: keyof typeof form, next: string) => setForm((current) => ({ ...current, [key]: next }));
  const formRef = useRef(form); formRef.current = form;
  const setRef = useRef(set); setRef.current = set;
  const Field = useMemo(() => ({ label, keyName, placeholder, area = false }: { label: string; keyName: keyof typeof form; placeholder?: string; area?: boolean }) => <label className="block"><span className="block text-[10px] font-bold uppercase tracking-wider text-slate-500 mb-1">{label}</span>{area ? <textarea rows={2} value={formRef.current[keyName]} onChange={(e) => setRef.current(keyName, e.target.value)} placeholder={placeholder} className="w-full px-3 py-2 text-xs border rounded-lg resize-y" /> : <input value={formRef.current[keyName]} onChange={(e) => setRef.current(keyName, e.target.value)} placeholder={placeholder} className="w-full px-3 py-2 text-xs border rounded-lg" />}</label>, []);
  const save = () => { if (!form.branchName.trim() || !form.location.trim()) { showToast('Branch name and Oman location are required', 'error'); return; } const record: BranchReport = { ...form, id: editingId || Date.now(), updatedAt: new Date().toISOString() }; setReports((current) => editingId ? current.map((item) => item.id === editingId ? record : item) : [record, ...current]); setForm({ ...emptyReport }); setEditingId(null); showToast('Branch report saved', 'success'); };
  const share = (items: BranchReport[]) => { const target = managerWhatsApp ? `https://wa.me/${managerWhatsApp}` : 'https://wa.me/'; window.open(`${target}?text=${encodeURIComponent(reportText(items))}`, '_blank'); showToast('Report opened in WhatsApp', 'success'); };
  const email = (items: BranchReport[]) => { window.open(`mailto:?subject=${encodeURIComponent('Branch Management Report')}&body=${encodeURIComponent(reportText(items))}`, '_blank'); showToast('Email report opened', 'success'); };
  const printPdf = (items: BranchReport[]) => { const popup = window.open('', '_blank'); if (!popup) return; popup.document.write(`<html><head><title>Branch Management Report</title><style>body{font:12px Arial;padding:24px;color:#18233d}h1{color:#172a52}table{border-collapse:collapse;width:100%;font-size:9px}th{background:#172a52;color:white;text-align:left}td,th{border:1px solid #ccd3df;padding:6px;vertical-align:top}</style></head><body><h1>Branch Management Report</h1><p>Generated ${new Date().toLocaleString()}</p>${tableHtml(items)}</body></html>`); popup.document.close(); popup.focus(); popup.print(); };
  const tableHtml = (items: BranchReport[]) => `<table><thead><tr>${headers.map((h) => `<th>${h}</th>`).join('')}</tr></thead><tbody>${items.map((r) => `<tr>${row(r).map((c) => `<td>${String(c ?? '').replace(/</g, '&lt;')}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
  const excel = (items: BranchReport[]) => download(`<html><meta charset="utf-8"><body>${tableHtml(items)}</body></html>`, `branch-management-${new Date().toISOString().slice(0, 10)}.xls`, 'application/vnd.ms-excel');
  const summary = useMemo(() => ({ branches: reports.length, complaints: reports.reduce((n, r) => n + (Number(r.openComplaints) || 0), 0), banking: reports.filter((r) => /active|live|yes/i.test(r.smartBanking)).length, onboarding: reports.reduce((n, r) => n + (Number(r.oldCustomerCount) || 0), 0) }), [reports]);
  return <div className="space-y-5 animate-fade-in">
    <div className="bg-[#0F1B33] rounded-2xl p-5 text-white shadow-ops-panel"><div className="flex items-center justify-between gap-4"><div className="flex items-center gap-3"><div className="p-2 rounded-lg bg-[#C9A227]/15 text-[#C9A227]"><Building2 className="w-5 h-5" /></div><div><h2 className="text-sm font-extrabold uppercase tracking-wider">Oman Branch Intelligence</h2><p className="text-[11px] text-[#8891A3] mt-1">Complete branch, competitor, marketing, customer and smart-banking table.</p></div></div><div className="hidden sm:flex gap-4 text-center font-mono"><div><b className="block text-[#C9A227]">{summary.branches}</b><span className="text-[9px] text-[#8891A3]">Branches</span></div><div><b className="block text-[#C9A227]">{summary.onboarding}</b><span className="text-[9px] text-[#8891A3]">Old customers</span></div><div><b className="block text-[#C9A227]">{summary.complaints}</b><span className="text-[9px] text-[#8891A3]">Complaints</span></div></div></div></div>
    <div className="bg-white rounded-2xl p-5 border border-slate-100 shadow-sm space-y-4"><div className="flex items-center justify-between"><h3 className="text-xs font-extrabold uppercase tracking-wider text-slate-700">Add / Update Branch Report</h3><span className="text-[10px] text-slate-400">All Oman locations</span></div><div className="grid sm:grid-cols-3 gap-3"><Field label="Branch name *" keyName="branchName" placeholder="Sohar Main Branch" /><label className="block"><span className="block text-[10px] font-bold uppercase tracking-wider text-slate-500 mb-1">Oman location *</span><select value={form.location} onChange={(e) => set('location', e.target.value)} className="w-full px-3 py-2 text-xs border rounded-lg bg-white"><option value="">Select governorate / city / area</option>{OMAN_LOCATIONS.map((location) => <option key={location}>{location}</option>)}</select></label><Field label="Manager" keyName="manager" /><Field label="Manager phone" keyName="phone" /><Field label="Status" keyName="status" placeholder="Active / Closed / Renovation" /><Field label="Staff count" keyName="staffCount" /><Field label="Staff attendance" keyName="staffAttendance" placeholder="90%" /><Field label="Staff behavior" keyName="staffBehavior" placeholder="Good / Needs coaching" /><Field label="Competitors around branch" keyName="competitorAround" area /><Field label="Marketing status" keyName="marketingStatus" area /><Field label="Leads / walk-ins" keyName="leads" /><Field label="What we need to improve" keyName="improveNeeded" area /><Field label="Smart banking status" keyName="smartBanking" placeholder="Active / Pending / Issue" /><Field label="Banking issues" keyName="bankingIssues" area /><Field label="Customer feedback score / 5" keyName="feedbackScore" /><Field label="Customer feedback" keyName="customerFeedback" area /><Field label="Old customers to onboard" keyName="oldCustomerCount" /><Field label="Old customer details" keyName="oldCustomerDetails" area /><Field label="Open complaints" keyName="openComplaints" /><Field label="Complaint notes" keyName="complaintNotes" area /><Field label="Remittance volume" keyName="remittanceVolume" /><Field label="Top corridor" keyName="topCorridor" /><Field label="Management notes" keyName="notes" area /></div><div className="flex gap-2"><button onClick={save} className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-indigo-600 text-white text-xs font-bold cursor-pointer"><Save className="w-4 h-4" /> {editingId ? 'Update report' : 'Save report'}</button>{editingId && <button onClick={() => { setForm({ ...emptyReport }); setEditingId(null); }} className="px-4 py-2 rounded-lg bg-slate-100 text-slate-600 text-xs font-bold cursor-pointer">Cancel</button>}</div></div>
    <div className="bg-white rounded-2xl p-4 border border-slate-100 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 mb-4"><div><h3 className="text-xs font-extrabold uppercase tracking-wider text-slate-700">All Branches Report Table</h3><p className="text-[10px] text-slate-400 mt-1">Scroll horizontally to see every category.</p></div><div className="flex flex-wrap gap-2"><button onClick={() => share(reports)} disabled={!reports.length} className="inline-flex items-center gap-1.5 px-3 py-2 rounded-lg bg-[#25D366] text-white text-[10px] font-bold cursor-pointer disabled:opacity-40"><MessageCircle className="w-3.5 h-3.5" /> WhatsApp</button><button onClick={() => email(reports)} disabled={!reports.length} className="inline-flex items-center gap-1.5 px-3 py-2 rounded-lg bg-slate-800 text-white text-[10px] font-bold cursor-pointer disabled:opacity-40"><Mail className="w-3.5 h-3.5" /> Email</button><button onClick={() => download(csv(reports), 'branch-management.csv', 'text/csv;charset=utf-8')} disabled={!reports.length} className="inline-flex items-center gap-1.5 px-3 py-2 rounded-lg bg-slate-100 text-slate-700 text-[10px] font-bold cursor-pointer disabled:opacity-40"><Download className="w-3.5 h-3.5" /> CSV</button><button onClick={() => excel(reports)} disabled={!reports.length} className="inline-flex items-center gap-1.5 px-3 py-2 rounded-lg bg-emerald-50 text-emerald-700 text-[10px] font-bold cursor-pointer disabled:opacity-40"><FileSpreadsheet className="w-3.5 h-3.5" /> Excel</button><button onClick={() => printPdf(reports)} disabled={!reports.length} className="inline-flex items-center gap-1.5 px-3 py-2 rounded-lg bg-rose-50 text-rose-700 text-[10px] font-bold cursor-pointer disabled:opacity-40"><FileText className="w-3.5 h-3.5" /> PDF / Print</button></div></div>
      <div className="overflow-x-auto rounded-xl border border-slate-200"><table className="w-full min-w-[1800px] text-[10px]"><thead><tr className="bg-[#172a52] text-white">{headers.map((header) => <th key={header} className="text-left px-3 py-3 font-bold whitespace-nowrap">{header}</th>)}<th className="px-3 py-3">Actions</th></tr></thead><tbody>{reports.length === 0 ? <tr><td colSpan={headers.length + 1} className="text-center py-12 text-slate-400">No reports yet. Add the first Oman branch above.</td></tr> : reports.map((r) => <tr key={r.id} className="border-t border-slate-100 odd:bg-white even:bg-slate-50/70 align-top">{row(r).map((cell, index) => <td key={index} className="px-3 py-3 max-w-[180px] whitespace-normal text-slate-600">{value(cell)}</td>)}<td className="px-3 py-3"><div className="flex flex-col gap-1.5"><button onClick={() => share([r])} className="inline-flex items-center gap-1 text-[#168a4b] font-bold cursor-pointer"><MessageCircle className="w-3 h-3" /> Share</button><button onClick={() => { setForm({ ...emptyReport, ...r }); setEditingId(r.id); window.scrollTo({ top: 0, behavior: 'smooth' }); }} className="text-indigo-600 font-bold text-left cursor-pointer">Edit</button><button onClick={() => setReports((current) => current.filter((item) => item.id !== r.id))} className="inline-flex items-center gap-1 text-rose-600 font-bold cursor-pointer"><Trash2 className="w-3 h-3" /> Delete</button></div></td></tr>)}</tbody></table></div></div>
    <p className="text-[10px] text-slate-400 px-1">PDF option opens the print dialog—choose “Save as PDF”. WhatsApp and email share the full report text; downloaded CSV/Excel/PDF files can be attached manually where required.</p>
  </div>;
}
